name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.14.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: pnpm

      - name: Audit dependencies
        run: pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev # When using an individual account, only use stack-name.
          work-dir: packages/infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}